name: horda_client
description: Connect your Flutter app to backends built with the Horda platform.
version: 0.23.0
homepage: https://github.com/horda-ai/dart_client

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  async: ^2.13.0
  collection: ^1.19.1
  horda_core: ^0.16.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  logging: ^1.3.0
  rxdart: ^0.28.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.7.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.0
